run:
  deadline: 5m

output:
  sort-results: true

linters:
  enable:
    - gofumpt
    - goimports
    - revive
    - depguard
    - goheader

linters-settings:
  goimports:
    local-prefixes: github.com/o11ydev/terraform-provider-zammad
  gofumpt:
    extra-rules: true
  goheader:
    template-path: .golangci.goheader.license
    regexp:
      YEAR: 202[2-9]
  errcheck:
    exclude: scripts/errcheck_excludes.txt
